name: capa
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  cross_file: ^0.3.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
